dist: trusty
sudo: required
language: go
go:
  - "1.10.x"
services:
  - docker
env:
  global:
    - DOCKER_IMAGE="fuzzyfrog/microcosm"
script:
  - go test -v ./...
  - docker build -t ${DOCKER_IMAGE}:${TRAVIS_COMMIT} -f docker/Dockerfile .
deploy:
  provider: script
  script: sh scripts/docker-push.sh $DOCKER_IMAGE
  on:
    tags: true
