{{- if .Release.IsInstall }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "microcosm.fullname" . }}
  labels:
    app: {{ include "microcosm.name" . }}
    chart: {{ include "microcosm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.microcosm.storageCapacity }}
  storageClassName: {{ .Values.microcosm.storageClassName }}
{{- end }}
