apiVersion: v1
kind: Service
metadata:
  name: {{ include "microcosm.fullname" . }}
  labels:
    app: {{ include "microcosm.name" . }}
    chart: {{ include "microcosm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.microcosm.serviceType }}
  selector:
    app: {{ include "microcosm.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: UDP
    port: 30301
    name: discovery
  - protocol: TCP
    port: 30303
    name: peers
  - protocol: TCP
    port: 8545
    name: jsonrpc
